/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author FireX
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        bodegaMenu = new javax.swing.JMenu();
        bodegaconsumibleMenu = new javax.swing.JMenuItem();
        bodegaprincipalMenu = new javax.swing.JMenuItem();
        informacionMenu = new javax.swing.JMenu();
        clienteMenu = new javax.swing.JMenuItem();
        facturasMenu = new javax.swing.JMenuItem();
        proveedoresMenu = new javax.swing.JMenuItem();
        vendedoresMenu = new javax.swing.JMenuItem();
        mercaderiaMenu = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        inventarioshowMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        bodegaMenu.setText("Bodega");

        bodegaconsumibleMenu.setText("Bodega de Consumibles");
        bodegaconsumibleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodegaconsumibleMenuActionPerformed(evt);
            }
        });
        bodegaMenu.add(bodegaconsumibleMenu);

        bodegaprincipalMenu.setText("Bodega Principal");
        bodegaMenu.add(bodegaprincipalMenu);

        jMenuBar1.add(bodegaMenu);

        informacionMenu.setText("Informacion Principal");

        clienteMenu.setText("Clientes");
        informacionMenu.add(clienteMenu);

        facturasMenu.setText("Facturas");
        informacionMenu.add(facturasMenu);

        proveedoresMenu.setText("Proveedores");
        informacionMenu.add(proveedoresMenu);

        vendedoresMenu.setText("Vendedores");
        informacionMenu.add(vendedoresMenu);

        jMenuBar1.add(informacionMenu);

        mercaderiaMenu.setText("Mercaderia");

        menuProducto.setText("Producto");
        mercaderiaMenu.add(menuProducto);

        inventarioshowMenu.setText("Inventario Showroom");
        mercaderiaMenu.add(inventarioshowMenu);

        jMenuBar1.add(mercaderiaMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bodegaconsumibleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodegaconsumibleMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodegaconsumibleMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bodegaMenu;
    private javax.swing.JMenuItem bodegaconsumibleMenu;
    private javax.swing.JMenuItem bodegaprincipalMenu;
    private javax.swing.JMenuItem clienteMenu;
    private javax.swing.JMenuItem facturasMenu;
    private javax.swing.JMenu informacionMenu;
    private javax.swing.JMenuItem inventarioshowMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenu mercaderiaMenu;
    private javax.swing.JMenuItem proveedoresMenu;
    private javax.swing.JMenuItem vendedoresMenu;
    // End of variables declaration//GEN-END:variables
}
